### ISSUE TITLE
Implementation

### ISSUE THREAD

**Issue by Suntrie** [the-banana-milk/Task2#2]
1. Что-то пошло не так с именами и областями видимости - классы именуются в соответствии с нотацией UpperCamelCase, области видимости, в большинстве случаев - private для данных (здесь для некоторых классов может быть логично применять package-private) и public для методов, доступных извне. Сейчас у нас конструктор и методы grep, например, с точки зрения объявленных областей видимости противоречат друг другу;

2. В случае публичных методов для объявления параметров и возвращаемых значений стремятся использовать интерфейс, а не реализацию;

3. Набор аргументов в ComLine пока не совсем соответствует заданию - word должен быть required, а вот -r является булевым флагом, Option, и может быть не задан (не указан при вызове, при этом в переменной окажется дефолтное false). Если не задан - слово = строка, в противном случае - основа для Regex;

4. Если верить [сэмплу](https://github.com/kohsuke/args4j/blob/master/args4j/examples/SampleMain.java), на основе распарсенных аргументов можно сразу создавать объект класса file;

5. Для вывода информации об ошибке лучше использовать специальный поток System.err + в текущей структуре ее лучше ловить в main -  иначе даже в случае возникновения ошибки выполнение программы будет продолжено. Кроме этого, ловить всегда стремятся максимально конкретные исключения - чтобы знать, какие ошибки мы отрабатываем, а какие приводят к полному "краху" запуска программы;

6. filterByWord, filterByRegex, ignoreCase структурно различаются очень слабо - в таком случае лучше вынести отдельный вспомогательный метод и обращаться к нему;

7. Если у нас есть фильтр = true,  сразу после нахождения которого мы вылетаем в break,  вроде логичнее (и менее ресурсоемко) его инициализировать false-ом еще до цикла;

8.  Писать все в одну строку ` else if (data.regex != null && data.file != null) newOne = new grep(data.regex, data.file);` с точки зрения стиля - очень не хорошо, это нечитаемо;

9. Вроде у Вас за счет required ни  word, ни regex, ни file сейчас стать равными null и не могут (при корректной обработке ошибок Вы даже не дойдете до места, где это будет актуально анализировать);

10.  В целом - алгоритмически main пока выглядит сильно переусложненно. Есть 2 варианта - с инверсией и без, есть получение списка слов по регэкспу или слову.  Можно вначале такой список получить, а потом засунуть в "отрицатель" в случае необходимости;

11. Если хочется выводить список ошибок с одинаковым текстом, лучше бы завести строковую константу и дергать ее - меньше шансов, что придется везде менять.

**Comment by Suntrie** [comment]
1. Осталось актуальным для полей Grep;

2. V

3. V

4. V

5. `} catch (Exception e) {` - ComLine, конструктор. Обычно в подобных случаях стремятся указывать отлавливаемые исключения максимально подробно (например, так проще анализировать программу. Кроме этого, если Вы выводите информацию об ошибке - не вполне понятно, зачем выводить stackTrace (он особо человекочитаемым не является и клиенту утилиты нужен вряд ли). Также неочевидно, зачем Вы в текущей версии кода ловите IllegalArgumentException в filterByWord;

6. Актуально;

7. -

8. -

9. Наверное почти ок,  но с учетом того, что проверку Вы в классе, отвечающем за логику, осуществляете в каждом методе,  наверное, ее все же стоило вынести в конструктор (актуальным из двух является единственный);

10. V

11.  -
___________
12. Для обеспечения корректной работы с ресурсами, в том числе, в ситуациях возникновения исключений, имеет смысл пользоваться паттерном [try-with-resources](https://docs.oracle.com/javase/tutorial/essential/exceptions/tryResourceClose.html);

13. Для хранения вспомогательных файлов в Maven-проектах можно использовать папку tests/resources.

**Comment by Thandriss** [comment]
1. Можно спросить по обозначениям, что значит "V" и точка?
6. Я вроде как вынесла общий метод. можно вынести ещё больше, но тогда он не будет применим к `.invert() и .ignoreCase()`. Можно я сделаю 2 выносных метода?
9. Я пытаюсь сейчас сделать так в конструкторе  
`Grep(String word, File file) {
        this.fileToWork = file;
        this.wordToWork = word;
        if (word.equals("")) throw new IllegalArgumentException("Данные введены не корректно");
    }`, но с вероятностью в 100% появляется исключение.

**Comment by Suntrie** [comment]
1. V - все ок, * - больше не актуально;
2. Поправьте меня, пожалуйста, но каких-то глобальных структурных различий между filterByWord и filterByRegex я сейчас не вижу;
3. С точки зрения логики выглядит разумно, не очень поняла про 100% вероятность. Я бы добавила проверку на то, выбрана ли одна из опций -r/-w также непосредственно в ComLine, т. к. это, по сути, в том числе логика обработки аргументов.

**Comment by Thandriss** [comment]
2. Да, я и говорю/пишу, что filterByWord и filterByRegex почти одинаковые и я могу для них вынести отдельный метод, но он уже не будет подходить для invert() и ignoreCase(). 
3. А на что эта проверка опций тогда влияет? Не совсем понятно. Я понимаю, что вместо `private boolean ex (String w) {
        return w.equals("") || w == null;
    }` и `if (ex(wordToWork)) throw new IllegalArgumentException();` я должна проверять аргумент в конструкторе, а не в методах, правильно? Но тесты, когда я делаю проверку в конструкторе, не работают. Точнее работают, но выбрасывается исключение с надписью "Данные введены не корректно". Там, где оно не должно выбрасываться.
